openapi: 3.0.0
info:
  title: 'Form API'
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000/
paths:
  /api/form:
    get:
      summary: 'Display a listing of the resource.'
      description: 'get all the data from the form'
      operationId: 10075a574aa9cbfc71a836a4ecb1d901
      responses:
        '200':
          description: OK
  /api/form/id:
    get:
      summary: 'Display the specified resource.'
      description: 'Get data from one form'
      operationId: 3250faab594a87129cd499be11a53839
      responses:
        '200':
          description: OK
